Feature/quest
tvbronswijk/memecity pull request #103
Opened 2018-12-19 22:28 UTC by RickvanBerlo

This Pull Request (PR) adds functionality to the game according to User Story #XXX

This PR...

* [x] has added functionality.
* [x] complies with the code style of the repository.
* [x] is up to date with the `dev` branch.

Also, I have...

* [x] Updated Taiga.

Please merge with care!

2018-12-19 22:41 UTC, Thomvdpas requested changes

2018-12-19 22:41 UTC, Thomvdpas commented on memecity.game/Game/States/PauseMenuState.cpp
> +		.with_read_only_menu_item("Strenght: improves attack")
Strength

2018-12-19 22:41 UTC, Thomvdpas commented on memecity.game/Game/States/PauseMenuState.cpp
> +		.with_read_only_menu_item("Endurance: improves movment speed")
Movement

2018-12-19 22:41 UTC, Thomvdpas commented on memecity.game/Game/States/PauseMenuState.cpp
> +		.with_read_only_menu_item("Charisma: better change of a getting away with a faulty pickpocket ")
Chance

2018-12-19 22:41 UTC, Thomvdpas commented on memecity.game/Game/States/PauseMenuState.cpp
> +		.with_read_only_menu_item("Intelligence: imporves pickpocket")
Improves

2018-12-19 22:41 UTC, Thomvdpas commented on memecity.game/Game/States/PauseMenuState.cpp
> +		.with_read_only_menu_item("Agility: imporves defence")
Improves defense

2018-12-19 22:41 UTC, Thomvdpas commented on memecity.game/Game/Builder/QuestBuilder.cpp
> +		"I drunk HAHAHA",
I'm

2018-12-19 22:47 UTC, RickvanBerlo commented on memecity.game/Game/Builder/QuestBuilder.cpp
> +		"I drunk HAHAHA",
was meer een refrence dat hij het niet meer goed kan uitspreken

2018-12-20 00:06 UTC, Thomvdpas approved these changes

2018-12-20 00:06 UTC, merged